ASSET_CATEGORIES = (
    "HVAC",
    "ELECTRICAL",
    "VERTICAL_TRANSPORTATION",
    "HOISTING",
)

FAILURE_MODES = (
    "TOOL_WEAR_FAILURE",
    "HEAT_DISSIPATION_FAILURE",
    "POWER_FAILURE",
    "OVERSTRAIN_FAILURE",
    "RANDOM_FAILURE",
)